/*
 * Stoatworks Labs - About window data for Radar.
 *
 * PROVISIONAL HAND COPY, 2026-09-25. This file is normally GENERATED by
 * stoatworks-backend/scripts/sync-about.py from the website's projects.json;
 * radar is not registered there yet, so this copy was written by hand in the
 * generated file's shape, with guide = "" because no user guide exists. The
 * first sync overwrites it -- and adds a "User guide" button at the END of
 * both plugins' parameter lists, which moves nothing (see Controls.h).
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Radar";
    inline constexpr auto slug = "radar";
    inline constexpr auto hook = "A PPI radar scope for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "https://stoatworks-labs.com/software/radar/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/radar";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
